site_name: RoboCup Small Size League Freiburg Documentation
site_url: https://example.com
nav:
    - Home: index.md
    - RoboCup Small Size League: robocup_ssl.md
    - Lab Course: lab_course.md
    - Software: software.md
    - Hardware: hardware.md
    - Field Setup: field_setup.md
theme: readthedocs
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - def_list
